import { chromium } from "@playwright/test";
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 390, height: 844 } })).newPage();
await page.goto("http://localhost:3100/", { waitUntil: "networkidle" });
await page.waitForTimeout(1500);
const info = () => page.evaluate(() => ({ rm: matchMedia("(prefers-reduced-motion: reduce)").matches, items: [...document.querySelectorAll("#meals article")].map((a) => { const n = a.firstElementChild; return { cls: n.className.slice(0, 40), clip: n.style.clipPath, attr: n.getAttribute("style"), rev: n.dataset.revealing, top: Math.round(n.getBoundingClientRect().top) }; }) }));
console.log("initial", JSON.stringify(await info(), null, 0));
await page.mouse.wheel(0, 5400);
await page.waitForTimeout(400);
console.log("mid", JSON.stringify((await info()).items.slice(0, 2)));
await page.waitForTimeout(1500);
console.log("after", JSON.stringify((await info()).items.slice(0, 2)));
await browser.close();
